[project]
id = "tdymtslljytdihkblvwu"

[functions.create-payment]
verify_jwt = true

[functions.create-stripe-account]
verify_jwt = true

[functions.release-payment]
verify_jwt = true

[functions.withdraw-wallet]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
