CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mission_id BIGINT REFERENCES missions(id) ON DELETE CASCADE,
  payeur_id TEXT NOT NULL,
  helper_id TEXT NOT NULL,
  stripe_session_id TEXT,
  stripe_payment_intent TEXT,
  montant DECIMAL(10,2) DEFAULT 0,
  frais DECIMAL(10,2) DEFAULT 2.00,
  statut TEXT DEFAULT 'en_attente',
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY IF EXISTS "payments_select" ON payments;
  DROP POLICY IF EXISTS "payments_insert" ON payments;
  DROP POLICY IF EXISTS "payments_update" ON payments;
END $$;

CREATE POLICY "payments_select" ON payments FOR SELECT USING (
  payeur_id = auth.uid()::text OR helper_id = auth.uid()::text
);
CREATE POLICY "payments_insert" ON payments FOR INSERT WITH CHECK (payeur_id = auth.uid()::text);
CREATE POLICY "payments_update" ON payments FOR UPDATE USING (
  payeur_id = auth.uid()::text OR helper_id = auth.uid()::text
);

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS stripe_account_id TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS stripe_onboarding BOOLEAN DEFAULT false;
