-- Table pour signaler un problème sur une mission
CREATE TABLE IF NOT EXISTS signals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mission_id BIGINT REFERENCES missions(id) ON DELETE CASCADE,
  conversation_id BIGINT REFERENCES conversations(id) ON DELETE CASCADE,
  reporter_id TEXT NOT NULL,
  raison TEXT NOT NULL,
  description TEXT,
  photos TEXT[] DEFAULT '{}',
  statut TEXT DEFAULT 'ouvert',
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE signals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "signals_select" ON signals FOR SELECT USING (
  reporter_id = auth.uid()::text
);

CREATE POLICY "signals_insert" ON signals FOR INSERT WITH CHECK (
  reporter_id = auth.uid()::text
);

-- Ajout colonne released_at sur payments
ALTER TABLE payments ADD COLUMN IF NOT EXISTS released_at TIMESTAMPTZ;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS refunded_at TIMESTAMPTZ;
