-- Table wallet (un par utilisateur)
CREATE TABLE IF NOT EXISTS wallets (
  user_id TEXT PRIMARY KEY,
  balance DECIMAL(10,2) DEFAULT 0 NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE wallets ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY IF EXISTS "wallets_select" ON wallets;
  DROP POLICY IF EXISTS "wallets_update" ON wallets;
END $$;

CREATE POLICY "wallets_select" ON wallets FOR SELECT USING (user_id = auth.uid()::text);
CREATE POLICY "wallets_update" ON wallets FOR UPDATE USING (user_id = auth.uid()::text);

-- Table transactions du wallet
CREATE TABLE IF NOT EXISTS wallet_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  type TEXT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  reference TEXT,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE wallet_transactions ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY IF EXISTS "wallet_transactions_select" ON wallet_transactions;
  DROP POLICY IF EXISTS "wallet_transactions_insert" ON wallet_transactions;
END $$;

CREATE POLICY "wallet_transactions_select" ON wallet_transactions FOR SELECT USING (user_id = auth.uid()::text);
CREATE POLICY "wallet_transactions_insert" ON wallet_transactions FOR INSERT WITH CHECK (user_id = auth.uid()::text);

-- Fonction pour créditer automatiquement le wallet
CREATE OR REPLACE FUNCTION credit_wallet(p_user_id TEXT, p_amount DECIMAL, p_reference TEXT, p_description TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO wallets (user_id, balance) VALUES (p_user_id, p_amount)
  ON CONFLICT (user_id) DO UPDATE SET balance = wallets.balance + p_amount, updated_at = now();

  INSERT INTO wallet_transactions (user_id, type, amount, reference, description)
  VALUES (p_user_id, 'credit', p_amount, p_reference, p_description);

  RETURN TRUE;
END;
$$;
