-- Réactions "bravo" sur missions terminées (Vague 1 — Feature 2)
-- Table légère : mission_id + user_id + type
CREATE TABLE IF NOT EXISTS reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mission_id BIGINT NOT NULL REFERENCES missions(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'bravo',
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (mission_id, user_id)
);

ALTER TABLE reactions ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY IF EXISTS "reactions_select" ON reactions;
  DROP POLICY IF EXISTS "reactions_insert" ON reactions;
  DROP POLICY IF EXISTS "reactions_delete" ON reactions;
END $$;

CREATE POLICY "reactions_select" ON reactions FOR SELECT USING (true);
CREATE POLICY "reactions_insert" ON reactions FOR INSERT WITH CHECK (user_id = auth.uid()::text);
CREATE POLICY "reactions_delete" ON reactions FOR DELETE USING (user_id = auth.uid()::text);
