-- ============================================================
-- 030 PUSH NOTIFICATIONS (APNs) + BLOCAGE D'UTILISATEUR
--
-- 1. push_tokens : enregistre le token APNs de chaque appareil.
--    RLS : un utilisateur ne lit/écrit/supprime que SES tokens.
--
-- 2. user_blocks : blocage mutuel entre utilisateurs (masquage
--    du feed, empêcher le contact). Un blocage se voit des deux
--    côtés : A bloque B => le contenu de B est masqué pour A ET
--    les messages de B sont refusés par A.
-- ============================================================

CREATE TABLE IF NOT EXISTS push_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  token TEXT NOT NULL,
  platform TEXT NOT NULL DEFAULT 'ios',
  created_at TIMESTAMPTZ DEFAULT now(),
  last_used_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (user_id, token)
);

ALTER TABLE push_tokens ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY IF EXISTS "push_tokens_select" ON push_tokens;
  DROP POLICY IF EXISTS "push_tokens_insert" ON push_tokens;
  DROP POLICY IF EXISTS "push_tokens_delete" ON push_tokens;
END $$;

CREATE POLICY "push_tokens_select" ON push_tokens
  FOR SELECT USING (user_id::text = auth.uid()::text);

CREATE POLICY "push_tokens_insert" ON push_tokens
  FOR INSERT WITH CHECK (
    user_id::text = auth.uid()::text
    AND token <> ''
  );

CREATE POLICY "push_tokens_delete" ON push_tokens
  FOR DELETE USING (user_id::text = auth.uid()::text);

-- Nettoyage : un token n'est valable que 60 jours en APNs (revoked
-- automatiquement au-delà sans ré-enregistrement actif).
CREATE OR REPLACE FUNCTION cleanup_stale_push_tokens()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  DELETE FROM push_tokens WHERE last_used_at < now() - INTERVAL '60 days';
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_push_token_used ON push_tokens;
CREATE TRIGGER on_push_token_used
  BEFORE INSERT OR UPDATE ON push_tokens
  FOR EACH ROW
  EXECUTE FUNCTION cleanup_stale_push_tokens();

-- ============ BLOCAGE UTILISATEUR ============

CREATE TABLE IF NOT EXISTS user_blocks (
  user_id TEXT NOT NULL,
  blocked_id TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (user_id, blocked_id)
);

ALTER TABLE user_blocks ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY IF EXISTS "user_blocks_select" ON user_blocks;
  DROP POLICY IF EXISTS "user_blocks_insert" ON user_blocks;
  DROP POLICY IF EXISTS "user_blocks_delete" ON user_blocks;
END $$;

CREATE POLICY "user_blocks_select" ON user_blocks
  FOR SELECT USING (user_id::text = auth.uid()::text);

CREATE POLICY "user_blocks_insert" ON user_blocks
  FOR INSERT WITH CHECK (user_id::text = auth.uid()::text AND blocked_id::text <> auth.uid()::text);

CREATE POLICY "user_blocks_delete" ON user_blocks
  FOR DELETE USING (user_id::text = auth.uid()::text);

CREATE INDEX IF NOT EXISTS idx_user_blocks_blocked ON user_blocks(blocked_id);